apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 8.8.1
  count: 1
  elasticsearchRef:
    name: eck
  config:
    kibana.host: https://eck-kb-http.${eck_namespace}.svc:5601
  configRef:
    secretName: es-credentials