apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "frozen-gp3"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "${frozen_pod_storage_class_iops}"
  throughput: "${frozen_pod_storage_class_throughput}"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer