apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "ml-io2-be"
provisioner: ebs.csi.aws.com
parameters:
  type: io2
  iops: "${ml_pod_storage_class_iops}"
  blockExpress : "true"
  allowAutoIOPSPerGBIncrease : "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer