apiVersion: v1
data:
  logstash.yml: |
    xpack.management.enabled: true
    xpack.management.elasticsearch.cloud_id: "xxxxxxx"
    xpack.management.elasticsearch.cloud_auth: "elastic:xxxxxx"
    xpack.management.logstash.poll_interval: 5s
    cloud.id: xxxxxxx
    cloud.auth: elastic:xxxxxx
    xpack.monitoring.elasticsearch.cloud_id: "xxxxxxx"
    xpack.monitoring.elasticsearch.cloud_auth: "elastic:xxxxxx"
    xpack.management.pipeline.id: ["pipeline*"]
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash