apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: eck
  name: eck-external-es-http
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: "eck"
    #elasticsearch.k8s.elastic.co/statefulset-name: "rally-es-hot"
    elasticsearch.k8s.elastic.co/node-master: "false"
  sessionAffinity: None
  type: LoadBalancer
